# Site settings
title: Pankil Shah
twitter_username: pankilshah
name: Pankil Shah

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/pankils
 - title: LinkedIn
   url: https://www.linkedin.com/in/pankilshah82

#Any buzzword skills you want to include
skills:
 - Project Management
#Work experience is required
roles:
 - title: Technical Program Manager
   start: 2015
   end: Ongoing
   employer: Estuate,Inc.
   description: Managed multiple strategic partner accounts globally averaging $1M in revenue along with new business development initiatives primarily in Cloud, Data Integration and Data Security. Grew accounts from ground up to $1M annually. Led 10+ consulting engagements in 3 years from the pre-sales stage to successful delivery of the project in terms of scope, deliverables, budget, client satisfaction and achievement of required business outcomes. Identified and led a cross-functional team to build integration solution around partner product solutions.
 - title: Senior Consultant
   start: 2013
   end: 2014
   employer: Estuate, Inc.
   description: Architected repeatable application retirement solution model for organizations to manage data archiving thus saving an average $150K in annual maintenance costs. Guided organizations to institute best practices for obfuscating identifiable information in the financial services, retail, and healthcare domains helping them comply with PII and PCI security norms.
 - title: Technical Product Manager
   start: 2011
   end: 2013
   employer: Estuate, Inc.
   description: 
 - title: Senior Technical Lead
   start: 2003
   end: 2011
   employer: Wipro Technologies
   description: 

#Education is required
education:
 - level: Master of Business Administration (M.B.A.)
   date: 2017
   subject: Global Management 
   school: UCLA Anderson School of Management
 - level: Master of Science (M.S.)
   date: 2007
   subject: Software Engineering
   school: Birla Institute of Technology & Science, Pilani

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: AI for Everyone
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September 16, 2013
    - title: Cost and Economics in Pricing Strategy
      link: https://www.coursera.org/specializations/algorithms
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2014
#udemy:



#List of interesting Github repo/projects to include - optional
github:
 - pankils/pankil.shah
 - pankils/sagemakerhelper

#Stackoverflow flair is optional
# stackoverflow:
#    profileurl: https://stackoverflow.com/users/258813/rhinds
#    flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
# I am an engineer with 15 years experience working in technology. I have primarily worked on the JVM, but have worked across a broad range of technologies thereon: Java, Groovy, Android, Coldfusion and most recently Scala. As well as spending a reasonable amount of time building applications for the web, which has given me an exposure to a range of javascript technologies over the years, through jQuery, extjs, knockout, backbone and most recently to React. <br/><br/>
#  I enjoy building interesting products, with a good Product Management focus and a good emphasis on good engineering principles and clean code (having worked across differing languages on the JVM, I recognise that good code is contextual).<br/><br/>
#  I have worked in large scale consultancy roles across Europe as well as a mix of startup experience (including one that was acquired) and I am currently the Chief Technology Officer at a legal-tech startup called <a href="https://www.basementcrowd.com" target="_blank">Basement Crowd</a> where we are building innovative products to serve the legal industry.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
# additionalinfo: |
#    <strong>Scala</strong>: My current role uses Scala as the primary language and have been building applications in Scala for the last two years. I am familiar with a range of Scala libraries, such as <a target="_blank" href="https://automateddeveloper.blogspot.com/2017/12/an-opinionated-guide-to-building-apis.html"> Akka-Http for building microservices</a> and <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/09/generic-programming-with-scala.html"> Shapeless for generic programming</a>, as well as familiar with a range of <a target="_blank" href="https://basementcrowd.com/2018/11/28/scala-the-aux-pattern-path-dependent-types/" >functional programming techniques available</a>.<br/><br/>
#    <strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks. I have worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others. <br/><br/>
#    <strong>Groovy</strong> I have used Groovy as a language in production for ~4 years and I am familiar with many of the languages features (such as writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>) and quirks (such as <a target="_blank" href="https://dzone.com/articles/groovy-retrospective-an-addendum-memory-usage-perm">memory leak issues</a>). <br/><br/>
#    <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito, <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/05/serverless-with-aws-lambda-scala.html">Lambda</a> and its more recent <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/10/machine-learning-with-aws-scala.html">Machine Learning capabilities</a>.<br/><br/>
#    <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS, Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
#    <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
#    I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>
#    As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="https://projects.spring.io/spring-social/">https://projects.spring.io/spring-social/</a>. <br/><br/>
#    I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="https://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
